name: safety_url
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.10
  dio: ^5.1.1
  dartpy: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
flutter:
  uses-material-design: true

  assets:
    - assets/brand_icon.png
    - assets/qr_icon.svg
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.png"
  min_sdk_android: 21
